version: "3"

services:

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  cache:
    image: redis
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - db
      - cache
    network_mode: host

volumes:
  mongodb_data_container: